import { Analytics } from "@vercel/analytics/next";
import type { Metadata, Viewport } from "next";
import { Inter, Lora } from "next/font/google";
import { notFound } from "next/navigation";

import "../globals.css";

import { InstallPrompt } from "@/components/install-prompt";
import { ServiceWorkerRegistration } from "@/components/service-worker-registration";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { FavoritesProvider } from "@/components/favorites-provider";
import { getMessages, isLocale, LOCALES, type Locale } from "@/i18n/config";
import { buildOpenGraph } from "@/lib/og";
import { SITE_URL } from "@/lib/site";

// Kept in sync by hand with `--color-paper` in globals.css and with
// `background_color`/`theme_color` in both `public/manifest.*.webmanifest`
// files — none of those can reference this constant, being CSS and static
// JSON respectively.
export const viewport: Viewport = {
  themeColor: "#2c3630",
  colorScheme: "dark",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

/**
 * Latin serif for headings. Japanese headings fall through to the OS Mincho
 * (see `--font-serif` in globals.css) rather than pulling a CJK webfont:
 * self-hosting Noto Serif JP means 248 font files and roughly 27 MB in the
 * build output, which this project deliberately avoids.
 */
const lora = Lora({
  subsets: ["latin"],
  weight: ["500", "600"],
  variable: "--font-lora",
  display: "swap",
});

/**
 * This is the root layout: there is no `app/layout.tsx`, so `[locale]` is the
 * topmost segment and can set `<html lang>` correctly for each language
 * without a client-side patch. `/` is served by `public/index.html`, which
 * redirects based on the browser's language.
 */
export function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}

export async function generateMetadata(
  props: LayoutProps<"/[locale]">,
): Promise<Metadata> {
  const { locale } = await props.params;
  if (!isLocale(locale)) return {};
  const messages = getMessages(locale);

  const title = `${messages.site.name} — ${messages.site.tagline}`;

  return {
    // Open Graph images need absolute URLs; this lets every page below pass
    // a plain relative path and have Next resolve it. Unlike `openGraph`
    // itself, `metadataBase` *is* inherited by child segments, so it only
    // needs setting once, here.
    metadataBase: new URL(SITE_URL),
    title: {
      default: title,
      template: `%s | ${messages.site.name}`,
    },
    description: messages.site.description,
    alternates: {
      languages: Object.fromEntries(
        LOCALES.map((candidate) => [candidate, `/${candidate}`]),
      ),
    },
    // Declared explicitly rather than through the `app/icon` convention, so
    // the same files can be referenced from `public/index.html`, which is a
    // plain static page outside the router. Generated by `npm run build:icons`.
    icons: {
      icon: [
        { url: "/favicon.ico", sizes: "16x16 32x32 48x48" },
        { url: "/icon-32.png", type: "image/png", sizes: "32x32" },
        { url: "/icon-192.png", type: "image/png", sizes: "192x192" },
        { url: "/icon-512.png", type: "image/png", sizes: "512x512" },
      ],
      apple: { url: "/apple-touch-icon.png", sizes: "180x180" },
    },
    // One manifest per locale rather than the `app/manifest.ts` file
    // convention: a manifest has exactly one `start_url`, and pointing every
    // locale at `/` would make the installed app open through the
    // redirect-splash `public/index.html` every launch. `name`/`description`
    // inside each `public/manifest.*.webmanifest` are kept in sync by hand
    // with `site.name`/`site.tagline`/`site.description` below — same
    // arrangement as the OG tags hardcoded in `public/index.html`.
    manifest: `/manifest.${locale}.webmanifest`,
    // `capable: true` is what actually makes iOS launch this as a
    // standalone app instead of a bookmark that opens in Safari.
    // `statusBarStyle` deliberately stays at the default rather than
    // `black-translucent`: that variant draws content under the status bar,
    // which would need `viewportFit: "cover"` plus safe-area padding
    // threaded through the header, footer and every sheet — out of scope
    // here.
    appleWebApp: {
      capable: true,
      title: messages.site.name,
      statusBarStyle: "default",
    },
    // Every page below repeats this in full rather than relying on
    // inheritance — see the comment on `buildOpenGraph` in `@/lib/og`.
    ...buildOpenGraph(locale, { title, description: messages.site.description }),
    // Not repeated per page: with no `twitter` field of its own, a page
    // inherits this unchanged, and Twitter/X falls back to the `og:*` tags
    // above for title/description/image.
    twitter: { card: "summary_large_image" },
  };
}

export default async function LocaleLayout(props: LayoutProps<"/[locale]">) {
  const { locale } = await props.params;
  if (!isLocale(locale)) notFound();

  return (
    <html lang={locale} className={`${inter.variable} ${lora.variable}`}>
      <body className="flex min-h-screen flex-col font-sans">
        <FavoritesProvider>
          <SiteHeader locale={locale as Locale} />
          <main className="flex-1">{props.children}</main>
          <SiteFooter locale={locale as Locale} />
        </FavoritesProvider>
        <InstallPrompt locale={locale as Locale} />
        <ServiceWorkerRegistration />
        <Analytics />
      </body>
    </html>
  );
}
